clf; 

uicontrol("Units", "normalized", "Position", [0.785 0.92 0.10 0.07], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 0 1], "String", ...
          "Individual information:");

uicontrol("Units", "normalized", "Position", [0.69 0.87 0.10 0.04], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Birth Month: ")
me_attribute_a = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.79 .87 .04 .04], 'Style','edit', "Callback", "me.birthM = 0;," + ...
          "me.birthM = str2num(get(me_attribute_a, 'String'));");

uicontrol("Units", "normalized", "Position", [0.84 0.87 0.10 0.04], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Birth Year: ")
me_attribute_b = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [0.93 .87 .05 .04], 'Style','edit', "Callback", "me.birthY = 0;," + ...
          "me.birthY = str2num(get(me_attribute_b, 'String'));");

uicontrol("Units", "normalized", "Position", [0.64 0.79 0.13 0.07], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Claim retirement (Year): ")
me_attribute_c = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.77 .79 .05 .07], 'Style','edit', "Callback", "me.claimAgeY = 0;," +...
          "me.claimAgeY = str2num(get(me_attribute_c, 'String'));");

uicontrol("Units", "normalized", "Position", [0.67 0.71 0.10 0.07], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Enter Death (Year): ")
me_attribute_d = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.77 .71 .05 .07], 'Style','edit', "Callback", "me.deathAgeY = 0;," + ...
          "me.deathAgeY = str2num(get(me_attribute_d, 'String'));");

uicontrol("Units", "normalized", "Position", [0.82 0.79 0.13 0.07], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Started Working (Year): ")
me_attribute_e = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.95 .79 .05 .07], 'Style','edit', "Callback", "me.workStartY = 0;," + ...
          "me.workStartY = str2num(get(me_attribute_e, 'String'));");

uicontrol("Units", "normalized", "Position", [0.82 0.71 0.12 0.07], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Ended Worked (Year): ")
me_attribute_f = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.94 .71 .05 .07], 'Style','edit', "Callback", "me.workEndY = 0;," + ...
          "me.workEndY = str2num(get(me_attribute_f, 'String'));");

uicontrol("Units", "normalized", "Position", [0.74 0.66 0.13 0.04], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Monthly Income: ")
me_attribute_g = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.87 .66 .06 .04], 'Style','edit', "Callback", ...
          "me.monthlyIncome = 0;," + ...
          "me.monthlyIncome = str2num(get(me_attribute_g, 'String'));");

is_sp = uicontrol("Units", "normalized", 'Style', 'checkbox', 'String', ...
        'Has Spouse', 'Position', [0.89 0.59 0.2 0.05], "FontSize", 15, ...
        "Callback", "if get(is_sp, 'Value') == 1, hasSpouse = true;, else, " + ...
        "hasSpouse = false;, end");

uicontrol("Units", "normalized", "Position", [0.785 0.58 0.10 0.07], ...
          "Style", "text", "FontSize", 15, "BackgroundColor", [1 0 1], ...
          "String", "Spouse information:");

uicontrol("Units", "normalized", "Position", [0.69 0.53 0.10 0.04], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Birth Month: ")
sp_attribute_a = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.79 .53 .04 .04], 'Style','edit', "Callback", "sp.birthM = 0;," + ...
          "sp.birthM = str2num(get(sp_attribute_a, 'String'));");

uicontrol("Units", "normalized", "Position", [0.84 0.53 0.10 0.04], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Birth Year: ")
sp_attribute_b = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [0.93 .53 .05 .04], 'Style','edit', "Callback", "sp.birthY = 0;," + ...
          "sp.birthY = str2num(get(sp_attribute_b, 'String'));");

uicontrol("Units", "normalized", "Position", [0.64 0.45 0.13 0.07], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Claim retirement (Year): ")
sp_attribute_c = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.77 .45 .05 .07], 'Style','edit', "Callback", "sp.claimAgeY = 0;," + ...
          "sp.claimAgeY = str2num(get(sp_attribute_c, 'String'));");

uicontrol("Units", "normalized", "Position", [0.67 0.37 0.10 0.07], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Enter Death (Year): ")
sp_attribute_d = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.77 .37 .05 .07], 'Style','edit', "Callback", "sp.deathAgeY = 0;," + ...
          "sp.deathAgeY = str2num(get(sp_attribute_d, 'String'));");

uicontrol("Units", "normalized", "Position", [0.82 0.45 0.13 0.07], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Started Working (Year): ")
sp_attribute_e = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.95 .45 .05 .07], 'Style','edit', "Callback", "sp.workStartY = 0;," + ...
          "sp.workStartY = str2num(get(sp_attribute_e, 'String'));");

uicontrol("Units", "normalized", "Position", [0.82 0.37 0.12 0.07], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Ended Worked (Year): ")
sp_attribute_f = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.94 .37 .05 .07], 'Style','edit', "Callback", "sp.workEndY = 0;," + ...
          "sp.workEndY = str2num(get(sp_attribute_f, 'String'));");

uicontrol("Units", "normalized", "Position", [0.74 0.32 0.13 0.04], "Style", ...
          "text", "FontSize", 15, "BackgroundColor", [1 1 1], "String", ...
          "Monthly Income: ")
sp_attribute_g = uicontrol('Units','normalized', 'BackgroundColor', ...
          [0 1 1], 'FontSize',15, 'ForegroundColor',[1 0 0], 'Position', ...
          [.87 .32 .06 .04], 'Style','edit', "Callback", "sp.monthlyIncome = 0;," + ...
          "sp.monthlyIncome = str2num(get(sp_attribute_g, 'String'));");

uicontrol("Units", "normalized", "Style", "text", "String", ...
          "Number of children: ", "BackgroundColor", [1 0 1], "FontSize", ...
          15, "Position", [0.74 0.27 0.15 0.04])
num_child = uicontrol("Units", "normalized", "Style", "text", "String", "0", ...
            "BackgroundColor", [1 0 1], "FontSize", 17, "Position", ...
            [0.89 0.27 0.03 0.04]);
child_slider = uicontrol("Units", "normalized", "Style", "slider", "Position", ...
               [0.73 0.23 0.20 0.03], "Max", 3, "Min", 0, "Callback", ...
               "set(num_child, 'String', " + ...
               "num2str(round(get(child_slider, 'Value'))))");

uicontrol("Units", "normalized", "Style", "text", "String", "Child_1:", ...
          "BackgroundColor", [1 0 1], "FontSize", 15, "Position", ...
          [0.7 0.18 0.07 0.04]);
uicontrol("Units", "normalized", "Style", "text", "String", "Birth(Y):", ...
          "BackgroundColor", [1 0 0], "FontSize", 15, "Position", ...
          [0.77 0.18 0.07 0.04])
uicontrol("Units", "normalized", "Style", "text", "String", "Birth(M):", ...
          "BackgroundColor", [1 0 0], "FontSize", 15, "Position", ...
          [0.89 0.18 0.07 0.04])
child_aY = uicontrol("Units", "normalized", "Style", "edit", "Position", ...
           [0.84 0.18 0.05 0.04], "FontSize", 15, "Callback", ...
           ["kids(1,1) = str2num(get(child_aY, 'String'));"]);
child_aM = uicontrol("Units", "normalized", "Style", "edit", "Position", ...
           [0.96 0.18 0.04 0.04], "FontSize", 15, "Callback", ...
           ["kids(1,2) = str2num(get(child_aM, 'String'));"]);

uicontrol("Units", "normalized", "Style", "text", "String", "Child_2:", ...
          "BackgroundColor", [1 0 1], "FontSize", 15, "Position", ...
          [0.7 0.14 0.07 0.04]);
uicontrol("Units", "normalized", "Style", "text", "String", "Birth(Y):", ...
          "BackgroundColor", [1 0 0], "FontSize", 15, "Position", ...
          [0.77 0.14 0.07 0.04])
uicontrol("Units", "normalized", "Style", "text", "String", "Birth(M):", ...
          "BackgroundColor", [1 0 0], "FontSize", 15, "Position", ...
          [0.89 0.14 0.07 0.04])
child_bY = uicontrol("Units", "normalized", "Style", "edit", "Position", ...
           [0.84 0.14 0.05 0.04], "FontSize", 15, "Callback", ...
           ["kids(2,1) = str2num(get(child_bY, 'String'));"]);
child_bM = uicontrol("Units", "normalized", "Style", "edit", "Position", ...
           [0.96 0.14 0.04 0.04], "FontSize", 15, "Callback", ...
           ["kids(2,2) = str2num(get(child_bM, 'String'));"]);

uicontrol("Units", "normalized", "Style", "text", "String", "Child_3:", ...
          "BackgroundColor", [1 0 1], "FontSize", 15, "Position", ...
          [0.7 0.10 0.07 0.04]);
uicontrol("Units", "normalized", "Style", "text", "String", "Birth(Y):", ...
          "BackgroundColor", [1 0 0], "FontSize", 15, "Position", ...
          [0.77 0.10 0.07 0.04])
uicontrol("Units", "normalized", "Style", "text", "String", "Birth(M):", ...
          "BackgroundColor", [1 0 0], "FontSize", 15, "Position", ...
          [0.89 0.10 0.07 0.04])
child_cY = uicontrol("Units", "normalized", "Style", "edit", "Position", ...
           [0.84 0.10 0.05 0.04], "FontSize", 15, "Callback", ...
           ["kids(3,1) = str2num(get(child_cY, 'String'));"]);
child_cM = uicontrol("Units", "normalized", "Style", "edit", "Position", ...
           [0.96 0.10 0.04 0.04], "FontSize", 15, "Callback", ...
           ["kids(3,2) = str2num(get(child_cM, 'String'));"]);

b = uicontrol("Units", "normalized", "Style", "pushbutton", "String", ...
    "Calculate", "FontSize", 15, "Position", [0.7 0.01 0.13 0.08], "Callback", ...
    ["if get(is_sp, 'Value') == 1, " + ...
    "  hasSpouse = true, " + ...
    "else, " + ...
    "  hasSpouse = false," + ...
    "  sp = struct('birthY', 0, 'birthM', 0, 'monthlyIncome', 0, 'workStartY', " + ...
    "       0, 'workEndY', 0, 'claimAgeY', 0, 'deathAgeY', 0), " + ...
    "end," + ...
    "if get(child_slider, 'Value') > 0, " + ...
    "  if size(kids, 2) > 1, " + ...
    "    hasChildren = true, " + ...
    "    save_child_num = round(get(child_slider, 'Value'))," + ...
    "    i = 1;," + ...
    "    save_num = save_child_num;, " + ...
    "    children = [];," + ...
    "    while save_num > 0, " + ...
    "      children = [children struct('birthY', kids(i, 1), 'birthM', kids(i, 2))];, " + ...
    "      i = i + 1;, " + ...
    "      save_num = save_num - 1;, " + ...
    "    end," + ...
    "  else, " + ...
    "    hasChildren = false, " + ...
    "    save_child_num = 0, " + ...
    "    children = [], " + ...
    "  end, " + ...
    "else, " + ...
    "  hasChildren = false, " + ...
    "  save_child_num = 0, " + ...
    "  children = [], " + ...
    "end," + ...
    "[months, B_me, B_sp, B_kids, B_HH, S_HH] = untitled_updated(" + ...
    "                     me, hasSpouse, sp, hasChildren, children);," + ...
    "untitled_gui," + ...
    "ax = axes('Units', 'normalized', 'Position', [0.06 0.62 0.58 0.35]);, " + ...
    "plot(months, B_me, 'LineWidth',1.3), " + ...
    "hold on," + ...
              "if hasSpouse, plot(months, B_sp, 'LineWidth',1.3), end," + ...
              "if hasChildren, plot(months, B_kids, 'LineWidth',1.3), end," + ...
              "plot(months, B_HH, 'k','LineWidth',1.8)," + ...
              "grid on, xlabel('Calendar Month Index'), ylabel('Benefit ($/mo)')," + ...
              "lg = {'You'};, if hasSpouse, lg{end+1}='Spouse';, end," + ...
              "if hasChildren, lg{end+1}='Children';, end," + ...
              "lg{end+1}='Household Total';," + ...
              "legend(lg,'Location','best'), title('Difference-Equation Benefit Flows')," + ...
              "ax = axes('Units', 'normalized', 'Position', [0.06 0.17 0.58 0.35]);, plot(months, S_HH, 'LineWidth',1.8), grid on," + ...
              "xlabel('Calendar Month Index'), ylabel('Cumulative Benefits ($)')," + ...
              "title('Household Lifetime Accumulation S_{t} = S_{t-1} + B_{t}')," + ...
              ...
              "set(me_attribute_a, 'String', num2str(me.birthM)), set(me_attribute_b, 'String', num2str(me.birthY))," + ...
              "set(me_attribute_c, 'String', num2str(me.claimAgeY)), set(me_attribute_d, 'String', num2str(me.deathAgeY))," + ...
              "set(me_attribute_e, 'String', num2str(me.workStartY)), set(me_attribute_f, 'String', num2str(me.workEndY))," + ...
              "set(me_attribute_g, 'String', num2str(me.monthlyIncome))," + ...
              "set(is_sp, 'Value', hasSpouse)," + ...
              "set(sp_attribute_a, 'String', num2str(sp.birthM)), set(sp_attribute_b, 'String', num2str(sp.birthY))," + ...
              "set(sp_attribute_c, 'String', num2str(sp.claimAgeY)), set(sp_attribute_d, 'String', num2str(sp.deathAgeY))," + ...
              "set(sp_attribute_e, 'String', num2str(sp.workStartY)), set(sp_attribute_f, 'String', num2str(sp.workEndY))," + ...
              "set(sp_attribute_g, 'String', num2str(sp.monthlyIncome))," + ...
              ...
              "set(num_child, 'String', num2str(save_child_num)), set(child_slider, 'Value', save_child_num)," + ...
              "if size(children, 2) == 1," + ...
              "set(child_aY, 'String', children(1,1).birthY), set(child_aM, 'String', children(1,1).birthM)," +...
              "set(child_bY, 'String', ''), set(child_bM, 'String', '')," + ...
              "set(child_cY, 'String', ''), set(child_cM, 'String', '')," + ...
              "elseif size(children, 2) == 2," + ...
              "set(child_aY, 'String', children(1,1).birthY), set(child_aM, 'String', children(1,1).birthM)," + ...
              "set(child_bY, 'String', children(1,2).birthY), set(child_bM, 'String', children(1,2).birthM)," + ...
              "set(child_cY, 'String', ''), set(child_cM, 'String', '')," + ...
              "elseif size(children, 2) == 3," + ...
              "set(child_aY, 'String', children(1,1).birthY), set(child_aM, 'String', children(1,1).birthM)," + ...
              "set(child_bY, 'String', children(1,2).birthY), set(child_bM, 'String', children(1,2).birthM)," + ...
              "set(child_cY, 'String', children(1,3).birthY), set(child_cM, 'String', children(1,3).birthM), end, " +...
              "kids = [str2num(get(child_aY, 'String')) str2num(get(child_aM, 'String'));" + ...
              "        str2num(get(child_bY, 'String')) str2num(get(child_bM, 'String')); " + ...
              "        str2num(get(child_cY, 'String')) str2num(get(child_cM, 'String'));];"]);
uicontrol("Units", "normalized", "Style","pushbutton","String", "Close", ...
          "Position", [0.85 0.01 0.13 0.08], "FontSize", 15, "Callback", ...
          "clear, clc, close all")